-- Vertabelo addendum - C4.2.5 traceability tables
-- Import this after data/sql_dump/protodb_schema_20260531.sql, or merge these
-- definitions into the full schema before importing into Vertabelo.

CREATE TABLE artifact_registry (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    artifact_type varchar(100) NOT NULL,
    phase varchar(50) NOT NULL,
    source_run varchar(255) NOT NULL,
    run_token varchar(100),
    file_path varchar(1024) NOT NULL,
    file_name varchar(255) NOT NULL,
    row_count integer,
    checksum varchar(128),
    file_size_bytes integer,
    status varchar(50) NOT NULL DEFAULT 'AVAILABLE',
    metadata_json text,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX uq_artifact_registry_lookup
    ON artifact_registry (source_run, artifact_type, file_path);

CREATE INDEX ix_artifact_registry_artifact_type
    ON artifact_registry (artifact_type);

CREATE INDEX ix_artifact_registry_phase
    ON artifact_registry (phase);

CREATE INDEX ix_artifact_registry_source_run
    ON artifact_registry (source_run);

CREATE INDEX ix_artifact_registry_run_token
    ON artifact_registry (run_token);

CREATE INDEX ix_artifact_registry_status
    ON artifact_registry (status);

CREATE INDEX ix_artifact_registry_phase_run
    ON artifact_registry (phase, source_run);


CREATE TABLE rule_runs (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_run varchar(255) NOT NULL UNIQUE,
    run_token varchar(100),
    alerts_file varchar(1024),
    summary_file varchar(1024),
    report_file varchar(1024),
    detailed_alert_count integer NOT NULL DEFAULT 0,
    grouped_alert_count integer NOT NULL DEFAULT 0,
    status varchar(50) NOT NULL DEFAULT 'AVAILABLE',
    metadata_json text,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now()
);

CREATE INDEX ix_rule_runs_source_run
    ON rule_runs (source_run);

CREATE INDEX ix_rule_runs_run_token
    ON rule_runs (run_token);

CREATE INDEX ix_rule_runs_status
    ON rule_runs (status);


CREATE TABLE model_registry (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    model_family varchar(100) NOT NULL,
    algorithm varchar(255) NOT NULL,
    source_run varchar(255) NOT NULL,
    run_token varchar(100),
    model_file varchar(1024),
    metadata_file varchar(1024),
    report_file varchar(1024),
    scores_file varchar(1024),
    feature_file varchar(1024),
    metrics_json text,
    status varchar(50) NOT NULL DEFAULT 'AVAILABLE',
    is_active boolean NOT NULL DEFAULT false,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX uq_model_registry_lookup
    ON model_registry (model_family, algorithm, source_run);

CREATE INDEX ix_model_registry_model_family
    ON model_registry (model_family);

CREATE INDEX ix_model_registry_algorithm
    ON model_registry (algorithm);

CREATE INDEX ix_model_registry_source_run
    ON model_registry (source_run);

CREATE INDEX ix_model_registry_run_token
    ON model_registry (run_token);

CREATE INDEX ix_model_registry_status
    ON model_registry (status);

CREATE INDEX ix_model_registry_is_active
    ON model_registry (is_active);


CREATE TABLE supervised_dataset_runs (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_run varchar(255) NOT NULL,
    run_token varchar(100),
    dataset_file varchar(1024),
    report_file varchar(1024),
    label_policy varchar(255) NOT NULL DEFAULT 'HUMAN_REVIEW_CONFIRMED_FRAUD_DISMISSED',
    positive_count integer NOT NULL DEFAULT 0,
    negative_count integer NOT NULL DEFAULT 0,
    usable_total_count integer NOT NULL DEFAULT 0,
    technical_ready boolean NOT NULL DEFAULT false,
    recommended_ready boolean NOT NULL DEFAULT false,
    strong_ready boolean NOT NULL DEFAULT false,
    status varchar(50) NOT NULL DEFAULT 'PENDING',
    metadata_json text,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now()
);

CREATE INDEX ix_supervised_dataset_runs_source_run
    ON supervised_dataset_runs (source_run);

CREATE INDEX ix_supervised_dataset_runs_run_token
    ON supervised_dataset_runs (run_token);

CREATE INDEX ix_supervised_dataset_runs_status
    ON supervised_dataset_runs (status);

